---
- name: Instalação do Docker
  hosts: ec2
  gather_facts: true
  any_errors_fatal: true
  become: yes

  vars:
    ansible_ssh_private_key_file: "~/.ssh/key"
    aws_account_id: "{{ lookup('env', 'AWS_ACCOUNT_ID') }}"

  tasks:
    - name: Adicionar chave de host ao known_hosts
      command: ssh-keyscan -H "{{ ansible_host }}" >> ~/.ssh/known_hosts

    - name: Instalar Docker
      shell: "curl -fsSL https://get.docker.com | sh"
      become: yes
      become_user: ubuntu

    - name: Instalar AWS CLI no Ubuntu
      become: yes
      apt:
        name: awscli
        state: present

    - name: Configurar Credenciais AWS
      become: yes
      set_fact:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      when: aws_access_key is not defined or aws_secret_key is not defined

    - name: Configurar Credenciais AWS
      become: yes
      command: "aws configure set aws_access_key_id={{ aws_access_key }} aws_secret_access_key={{ aws_secret_key }} region=us-east-1"

    - name: Login no Amazon ECR
      shell: "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 455968579615.dkr.ecr.us-east-1.amazonaws.com"
      become: yes

    - name: Pull da imagem
      vars:
        aws_account_id: ""
      command: "docker pull 455968579615.dkr.ecr.us-east-1.amazonaws.com/authsure:latest"

