---
- name: Instalação do Docker
  hosts: ec2
  gather_facts: true
  any_errors_fatal: true
  become: yes

  tasks:
    - name: Adicionar chave de host ao known_hosts
      command: ssh-keyscan -H "authsure" >> ~/.ssh/known_hosts

    - name: Instalar Docker
      apt:
        name: docker.io
        state: present
      become_user: ubuntu

  vars:
    ansible_ssh_private_key_file: "~/.ssh/key"
