---
- name: Instalação do Docker
  hosts: ec2
  gather_facts: true
  any_errors_fatal: true
  become: yes

  tasks:
    - name: Adicionar chave de host ao known_hosts
      command: ssh-keyscan -H "{{ ansible_host }}" >> ~/.ssh/known_hosts

    - name: Instalar Docker
      shell: "curl -fsSL https://get.docker.com | sh"
      become: yes
      become_user: ubuntu

    - name: Autenticação no ECR
      command: "aws configure set aws_access_key_id {{ lookup('env', 'AWS_ACCESS_KEY_ID') }} && aws configure set aws_secret_access_key {{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }} && aws configure set aws_session_token {{ lookup('env', 'AWS_TOKEN') }} && aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin {{ lookup('env', 'AWS_ACCOUNT_ID') }}.dkr.ecr.us-east-1.amazonaws.com"
      become: yes
      become_user: ubuntu

  vars:
    ansible_ssh_private_key_file: "~/.ssh/key"
