---
- name: Instalação do Docker
  hosts: ec2

  gather_facts: true
  any_errors_fatal: true
  become: yes

  vars:
    ansible_ssh_private_key_file: "~/.ssh/key"
      
  tasks:
    - name: Adicionar chave de host ao known_hosts
      command: ssh-keyscan -H "{{ ansible_host }}" >> ~/.ssh/known_hosts


    - name: Installing unzip
      apt: 
        name: unzip
        state: latest
      tags: Installed


    - name: Download file
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscliv2.zip"
      tags:
        - download

    - name: unzip
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp/
        remote_src: yes

    - name: awscli-bundle
      shell: ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
      args: 
       chdir: /tmp/
      tags: Installed_awscli-bundle
    
    - name: Configure AWS.
      shell: aws configure set {{ item.key }} {{ item.value }} --profile default
      with_dict:
        aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
        aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
        region: "us-east-1"
        aws_session_token: "{{ lookup('env', 'AWS_TOKEN') }}"
      become: true
      changed_when: false

    - name: Login na AWS ECR
      shell: "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 455968579615.dkr.ecr.us-east-1.amazonaws.com"
      become: yes
      become_user: ubuntu


    # - name: add token
    #   shell: echo -e {{ item.key }} {{ item.value }}
    #   with_dict:
    #     aws_session_token: "{{ lookup('env', 'AWS_TOKEN') }}"

    - name: Instalar Docker
      shell: "curl -fsSL https://get.docker.com | sh"
      become: yes
      become_user: ubuntu

    - name: Pull da imagem do ECR
      shell: docker pull 455968579615.dkr.ecr.us-east-1.amazonaws.com/authsure:latest
