---
- name: Instalação do Docker
  hosts: authsure
  gather_facts: true
  any_errors_fatal: true
  become: yes

  tasks:
    - name: Instalar Docker
      apt:
        name: docker.io
        state: present
      become_user: ubuntu
