---
- name: Instalação do Docker
  hosts: ec2

  gather_facts: true
  any_errors_fatal: true
  become: yes

  vars:
    ansible_ssh_private_key_file: "~/.ssh/key"
      
  tasks:
    - name: Adicionar chave de host ao known_hosts
      command: ssh-keyscan -H "{{ ansible_host }}" >> ~/.ssh/known_hosts


    - name: Installing unzip
      apt: 
        name: unzip
        state: latest
      tags: Installed


    - name: Download file
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscliv2.zip"
      tags:
        - download

    - name: unzip
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp/
        remote_src: yes
    
    # - name: Configure AWS.
    #   shell: "aws configure set {{ item.key }} {{ item.value }} --profile {{ aws_profile }}"
    #   no_log: True
    #   with_dict:
    #     aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
    #     aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
    #     region: "us-east-1"
    #   become_user: "{{ aws_system_user }}"
    #   changed_when: false

    - name: Instalar Docker
      shell: "curl -fsSL https://get.docker.com | sh"
      become: yes
      become_user: ubuntu

    - name: Pull da imagem do ECR
      script:
        cmd: |
          docker pull 455968579615.dkr.ecr.us-east-1.amazonaws.com/authsure:latest
